# Generated by Django 5.0.2 on 2024-02-15 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universitycampus',
            options={},
        ),
        migrations.AlterModelTable(
            name='universitycampus',
            table='university campus',
        ),
    ]
