# Generated by Django 5.0.2 on 2024-02-15 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0002_alter_universitycampus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universitycampus',
            options={'verbose_name': 'university campus'},
        ),
        migrations.AlterModelTable(
            name='universitycampus',
            table=None,
        ),
    ]
