# Generated by Django 5.0.2 on 2024-02-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0002_transaction_delete_transactions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='data',
            new_name='date',
        ),
    ]
